// Mode 1 PIDs
#define PID_ENGINE_LOAD 0x04
#define PID_COOLANT_TEMP 0x05
#define PID_SHORT_TERM_FUEL_TRIM_1 0x06
#define PID_LONG_TERM_FUEL_TRIM_1 0x07
#define PID_SHORT_TERM_FUEL_TRIM_2 0x08
#define PID_LONG_TERM_FUEL_TRIM_2 0x09
#define PID_FUEL_PRESSURE 0x0A
#define PID_INTAKE_MAP 0x0B
#define PID_RPM 0x0C
#define PID_SPEED 0x0D
#define PID_TIMING_ADVANCE 0x0E
#define PID_INTAKE_TEMP 0x0F
#define PID_MAF_FLOW 0x10
#define PID_THROTTLE 0x11
#define PID_AUX_INPUT 0x1E
#define PID_RUNTIME 0x1F
#define PID_DISTANCE_WITH_MIL 0x21
#define PID_COMMANDED_EGR 0x2C
#define PID_EGR_ERROR 0x2D
#define PID_COMMANDED_EVAPORATIVE_PURGE 0x2E
#define PID_FUEL_LEVEL 0x2F
#define PID_WARMS_UPS 0x30
#define PID_DISTANCE 0x31
#define PID_EVAP_SYS_VAPOR_PRESSURE 0x32
#define PID_BAROMETRIC 0x33
#define PID_CATALYST_TEMP_B1S1 0x3C
#define PID_CATALYST_TEMP_B2S1 0x3D
#define PID_CATALYST_TEMP_B1S2 0x3E
#define PID_CATALYST_TEMP_B2S2 0x3F
#define PID_CONTROL_MODULE_VOLTAGE 0x42
#define PID_ABSOLUTE_ENGINE_LOAD 0x43
#define PID_AIR_FUEL_EQUIV_RATIO 0x44
#define PID_RELATIVE_THROTTLE_POS 0x45
#define PID_AMBIENT_TEMP 0x46
#define PID_ABSOLUTE_THROTTLE_POS_B 0x47
#define PID_ABSOLUTE_THROTTLE_POS_C 0x48
#define PID_ACC_PEDAL_POS_D 0x49
#define PID_ACC_PEDAL_POS_E 0x4A
#define PID_ACC_PEDAL_POS_F 0x4B
#define PID_COMMANDED_THROTTLE_ACTUATOR 0x4C
#define PID_TIME_WITH_MIL 0x4D
#define PID_TIME_SINCE_CODES_CLEARED 0x4E
#define PID_ETHANOL_FUEL 0x52
#define PID_FUEL_RAIL_PRESSURE 0x59
#define PID_HYBRID_BATTERY_PERCENTAGE 0x5B
#define PID_ENGINE_OIL_TEMP 0x5C
#define PID_FUEL_INJECTION_TIMING 0x5D
#define PID_ENGINE_FUEL_RATE 0x5E
#define PID_ENGINE_TORQUE_DEMANDED 0x61
#define PID_ENGINE_TORQUE_PERCENTAGE 0x62
#define PID_ENGINE_REF_TORQUE 0x63

// Mode 1 channel IDs
#define PID_ENGINE_LOAD_ID 0x104
#define PID_COOLANT_TEMP_ID 0x105
#define PID_SHORT_TERM_FUEL_TRIM_1_ID 0x106
#define PID_LONG_TERM_FUEL_TRIM_1_ID 0x107
#define PID_SHORT_TERM_FUEL_TRIM_2_ID 0x108
#define PID_LONG_TERM_FUEL_TRIM_2_ID 0x109
#define PID_FUEL_PRESSURE_ID 0x10A
#define PID_INTAKE_MAP_ID 0x10B
#define PID_RPM_ID 0x10C
#define PID_SPEED_ID 0x10D
#define PID_TIMING_ADVANCE_ID 0x10E
#define PID_INTAKE_TEMP_ID 0x10F
#define PID_MAF_FLOW_ID 0x110
#define PID_THROTTLE_ID 0x111
#define PID_AUX_INPUT_ID 0x11E
#define PID_RUNTIME_ID 0x11F
#define PID_DISTANCE_WITH_MIL_ID 0x121
#define PID_COMMANDED_EGR_ID 0x12C
#define PID_EGR_ERROR_ID 0x12D
#define PID_COMMANDED_EVAPORATIVE_PURGE_ID 0x12E
#define PID_FUEL_LEVEL_ID 0x12F
#define PID_WARMS_UPS_ID 0x130
#define PID_DISTANCE_ID 0x131
#define PID_EVAP_SYS_VAPOR_PRESSURE_ID 0x132
#define PID_BAROMETRIC_ID 0x133
#define PID_CATALYST_TEMP_B1S1_ID 0x13C
#define PID_CATALYST_TEMP_B2S1_ID 0x13D
#define PID_CATALYST_TEMP_B1S2_ID 0x13E
#define PID_CATALYST_TEMP_B2S2_ID 0x13F
#define PID_CONTROL_MODULE_VOLTAGE_ID 0x142
#define PID_ABSOLUTE_ENGINE_LOAD_ID 0x143
#define PID_AIR_FUEL_EQUIV_RATIO_ID 0x144
#define PID_RELATIVE_THROTTLE_POS_ID 0x145
#define PID_AMBIENT_TEMP_ID 0x146
#define PID_ABSOLUTE_THROTTLE_POS_B_ID 0x147
#define PID_ABSOLUTE_THROTTLE_POS_C_ID 0x148
#define PID_ACC_PEDAL_POS_D_ID 0x149
#define PID_ACC_PEDAL_POS_E_ID 0x14A
#define PID_ACC_PEDAL_POS_F_ID 0x14B
#define PID_COMMANDED_THROTTLE_ACTUATOR_ID 0x14C
#define PID_TIME_WITH_MIL_ID 0x14D
#define PID_TIME_SINCE_CODES_CLEARED_ID 0x14E
#define PID_ETHANOL_FUEL_ID 0x152
#define PID_FUEL_RAIL_PRESSURE_ID 0x159
#define PID_HYBRID_BATTERY_PERCENTAGE_ID 0x15B
#define PID_ENGINE_OIL_TEMP_ID 0x15C
#define PID_FUEL_INJECTION_TIMING_ID 0x15D
#define PID_ENGINE_FUEL_RATE_ID 0x15E
#define PID_ENGINE_TORQUE_DEMANDED_ID 0x161
#define PID_ENGINE_TORQUE_PERCENTAGE_ID 0x162
#define PID_ENGINE_REF_TORQUE_ID 0x163


// Mode 9 PIDs
#define OBFCM_TOTAL_DISTANCE_TRAVELED_RECENT                    0x17	// idx = 1
#define OBFCM_TOTAL_DISTANCE_TRAVELED_LIFETIME                  0x17	// idx = 2
#define OBFCM_TOTAL_FUEL_TRAVELED_RECENT                        0x17	// idx = 3
#define OBFCM_TOTAL_FUEL_TRAVELED_LIFETIME                      0x17	// idx = 4
#define OBFCM_PEV_DIST_CHARGE_DEPL_ENG_OFF_RECENT               0x1A	// idx = 5
#define OBFCM_PEV_DIST_CHARGE_DEPL_ENG_OFF_LIFETIME             0x1A	// idx = 6
#define OBFCM_PEV_DIST_CHARGE_DEPL_ENG_ON_RECENT                0x1A	// idx = 7
#define OBFCM_PEV_DIST_CHARGE_DEPL_ENG_ON_LIFETIME              0x1A	// idx = 8
#define OBFCM_PEV_DIST_CHARGE_INCREASING_RECENT                 0x1A	// idx = 9
#define OBFCM_PEV_DIST_CHARGE_INCREASING_LIFETIME               0x1A	// idx = 10
#define OBFCM_PEV_FUEL_CONSUMED_CHARGE_DEPL_RECENT              0x1B	// idx = 11
#define OBFCM_PEV_FUEL_CONSUMED_CHARGE_DEPL_LIFETIME            0x1B	// idx = 12
#define OBFCM_PEV_FUEL_CONSUMED_CHARGE_INCR_RECENT              0x1B	// idx = 13
#define OBFCM_PEV_FUEL_CONSUMED_CHARGE_INCR_LIFETIME            0x1B	// idx = 14
#define OBFCM_PEV_GRID_ENERGY_CHARGE_DEPL_ENG_OFF_RECENT        0x1C	// idx = 15
#define OBFCM_PEV_GRID_ENERGY_CHARGE_DEPL_ENG_OFF_LIFETIME		0x1C	// idx = 16
#define OBFCM_PEV_GRID_ENERGY_CHARGE_DEPL_ENG_ON_RECENT		    0x1C	// idx = 17
#define OBFCM_PEV_GRID_ENERGY_CHARGE_DEPL_ENG_ON_LIFETIME	    0x1C	// idx = 18
#define OBFCM_PEV_GRID_ENERGY_IN_BATTERY_RECENT				    0x1C	// idx = 19
#define OBFCM_PEV_GRID_ENERGY_IN_BATTERY_LIFETIME			    0x1C	// idx = 20

// Mode 9 Channel IDs
#define OBFCM_TOTAL_DISTANCE_TRAVELED_RECENT_ID                    0x9171	// idx = 1
#define OBFCM_TOTAL_DISTANCE_TRAVELED_LIFETIME_ID                  0x9172	// idx = 2
#define OBFCM_TOTAL_FUEL_TRAVELED_RECENT_ID                        0x9173	// idx = 3
#define OBFCM_TOTAL_FUEL_TRAVELED_LIFETIME_ID                      0x9174	// idx = 4
#define OBFCM_PEV_DIST_CHARGE_DEPL_ENG_OFF_RECENT_ID               0x91A1	// idx = 5
#define OBFCM_PEV_DIST_CHARGE_DEPL_ENG_OFF_LIFETIME_ID             0x91A2	// idx = 6
#define OBFCM_PEV_DIST_CHARGE_DEPL_ENG_ON_RECENT_ID                0x91A3	// idx = 7
#define OBFCM_PEV_DIST_CHARGE_DEPL_ENG_ON_LIFETIME_ID              0x91A4	// idx = 8
#define OBFCM_PEV_DIST_CHARGE_INCREASING_RECENT_ID                 0x91A5	// idx = 9
#define OBFCM_PEV_DIST_CHARGE_INCREASING_LIFETIME_ID               0x91A6	// idx = 10
#define OBFCM_PEV_FUEL_CONSUMED_CHARGE_DEPL_RECENT_ID              0x91B1	// idx = 11
#define OBFCM_PEV_FUEL_CONSUMED_CHARGE_DEPL_LIFETIME_ID            0x91B2	// idx = 12
#define OBFCM_PEV_FUEL_CONSUMED_CHARGE_INCR_RECENT_ID              0x91B3	// idx = 13
#define OBFCM_PEV_FUEL_CONSUMED_CHARGE_INCR_LIFETIME_ID            0x91B4	// idx = 14
#define OBFCM_PEV_GRID_ENERGY_CHARGE_DEPL_ENG_OFF_RECENT_ID        0x91C1	// idx = 15
#define OBFCM_PEV_GRID_ENERGY_CHARGE_DEPL_ENG_OFF_LIFETIME_ID		0x91C2	// idx = 16
#define OBFCM_PEV_GRID_ENERGY_CHARGE_DEPL_ENG_ON_RECENT_ID		    0x91C3	// idx = 17
#define OBFCM_PEV_GRID_ENERGY_CHARGE_DEPL_ENG_ON_LIFETIME_ID	    0x91C4	// idx = 18
#define OBFCM_PEV_GRID_ENERGY_IN_BATTERY_RECENT_ID				    0x91C5	// idx = 19
#define OBFCM_PEV_GRID_ENERGY_IN_BATTERY_LIFETIME_ID			    0x91C6	// idx = 20

// Mode 1 MULTIPIDs PIDs
#define MULTIPID_ENGINE_FUEL_RATE_GS 0x9D
#define MULTIPID_VEHICLE_FUEL_RATE_GS 0x9D

// Mode 1 MULTIPIDs Channel IDs
#define MULTIPID_ENGINE_FUEL_RATE_GS_ID 0x19D1
#define MULTIPID_VEHICLE_FUEL_RATE_GS_ID 0x19D2

typedef struct
{
	byte		idx;					// idx identifying the parameter in the data structure
    byte		pid;					// PID: OBD Parameter ID (PID) or InfoType ID (ITID)
    uint16_t	id;					    // channel ID in JRCMATICS systems
	byte		nrOfChForMsg;		    // number of channels in message
	byte		curMsg;					// current channel
	byte		service;				// standard diagnostics service: 0x01..0x0A; or custom service: 0x22
	byte		startBit;				// start bit position where the channel is found
	byte		length;					// lenght of the information in bits
	float		gain;                   // engineering scale factor
	float		offset;				    // engineering offset 
	int		    value;			        // engineered value
}
DS_CAN_MSG;

typedef enum {
    PROTO_AUTO = 0x0,
    PROTO_ISO_9141_2 = 0x3,
    PROTO_KWP2000_5KBPS = 0x4,
    PROTO_KWP2000_FAST = 0x5,
    PROTO_CAN_11B_500K = 0x6,
    PROTO_CAN_29B_500K = 0x7,
    PROTO_CAN_29B_250K = 0x8,
    PROTO_CAN_11B_250K = 0x9,
    PROTO_J1939 = 0xB,
} OBD_PROTOCOLS;

// states
typedef enum {
    OBD_DISCONNECTED = 0,
    OBD_CONNECTING = 1,
    OBD_CONNECTED = 2,
    OBD_FAILED = 3
} OBD_STATES;
